<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PedidoBlingStaging extends Model
{
    protected $table = 'pedidos_bling_staging';

    protected $fillable = [
        'bling_id',
        'bling_account',
        'numero_pedido',
        'numero_loja',
        'data_pedido',
        'cliente_nome',
        'cliente_documento',
        'total_produtos',
        'total_pedido',
        'frete',
        'custo_frete',
        'comissao_calculada',
        'subsidio_pix',
        'base_imposto',
        'percentual_imposto',
        'valor_imposto',
        'canal',
        'nota_fiscal',
        'nfe_numero',
        'nfe_chave_acesso',
        'nfe_valor',
        'nfe_xml_url',
        'nfe_pdf_url',
        'situacao_id',
        'observacoes',
        'itens',
        'parcelas',
        'dados_originais',
        'status',
        'estoque_sincronizado',
        'planilha_shopee',
        'ml_tipo_anuncio',
        'ml_tipo_frete',
        'ml_tem_rebate',
        'ml_valor_rebate',
        'ml_sale_fee',
        'ml_frete_custo',
        'ml_frete_receita',
        'ml_order_id',
        'ml_shipping_id',
        'dest_cep',
        'dest_cidade',
        'dest_uf',
        'peso_bruto',
        'embalagem_largura',
        'embalagem_altura',
        'embalagem_comprimento',
    ];

    protected $casts = [
        'data_pedido' => 'date',
        'total_produtos' => 'decimal:2',
        'total_pedido' => 'decimal:2',
        'frete' => 'decimal:2',
        'custo_frete' => 'decimal:2',
        'comissao_calculada' => 'decimal:2',
        'subsidio_pix' => 'decimal:2',
        'base_imposto' => 'decimal:2',
        'percentual_imposto' => 'decimal:2',
        'valor_imposto' => 'decimal:2',
        'nfe_valor' => 'decimal:2',
        'estoque_sincronizado' => 'boolean',
        'planilha_shopee' => 'boolean',
        'ml_tem_rebate' => 'boolean',
        'ml_valor_rebate' => 'decimal:2',
        'ml_sale_fee' => 'decimal:2',
        'ml_frete_custo' => 'decimal:2',
        'ml_frete_receita' => 'decimal:2',
        'peso_bruto' => 'decimal:3',
        'embalagem_largura' => 'decimal:2',
        'embalagem_altura' => 'decimal:2',
        'embalagem_comprimento' => 'decimal:2',
        'itens' => 'array',
        'parcelas' => 'array',
        'dados_originais' => 'array',
    ];
}
